# pipeline:
#   test:
#     image: golang
#     commands:
#       - go get
#       - go test

# services:
#   database:
#     image: postgres
#     environment:
#       - POSTGRES_USER=postgres
#       - POSTGRES_DB=test

pipeline:
  ping:
    image: postgres
    environment:
      - PGUSER=postgres
      - PGPASSWORD=pgpass
    commands:
      - sleep 20
      - |
        psql -U postgres -d test -h database \
          -c "SELECT * FROM pg_catalog.pg_tables;"

services:
  database:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pgpass
