# pipeline:
#   test:
#     image: golang
#     commands:
#       - go get
#       - go test

# services:
#   database:
#     image: postgres
#     environment:
#       - POSTGRES_USER=postgres
#       - POSTGRES_DB=test

pipeline:


# services:
  postgres:
    image: postgres
    detach: true
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pgpass
    # ports:
    #   - '15432:5432'

  Run Something:
    image: busybox
    commands:
      - echo 'hello'
